# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preview.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Preview(object):
    def setupUi(self, Preview):
        Preview.setObjectName("Preview")
        Preview.resize(629, 887)
        self.verticalLayout = QtWidgets.QVBoxLayout(Preview)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Preview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(425, 550))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_checks = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_checks.sizePolicy().hasHeightForWidth())
        self.frame_checks.setSizePolicy(sizePolicy)
        self.frame_checks.setMinimumSize(QtCore.QSize(0, 37))
        self.frame_checks.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_checks.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_checks.setObjectName("frame_checks")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_checks)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_Filt1 = QtWidgets.QCheckBox(self.frame_checks)
        self.checkBox_Filt1.setObjectName("checkBox_Filt1")
        self.horizontalLayout.addWidget(self.checkBox_Filt1)
        self.checkBox_Filt2 = QtWidgets.QCheckBox(self.frame_checks)
        self.checkBox_Filt2.setObjectName("checkBox_Filt2")
        self.horizontalLayout.addWidget(self.checkBox_Filt2)
        self.pushButton_Paste = QtWidgets.QPushButton(self.frame_checks)
        self.pushButton_Paste.setObjectName("pushButton_Paste")
        self.horizontalLayout.addWidget(self.pushButton_Paste)
        self.pushButton_Cancel = QtWidgets.QPushButton(self.frame_checks)
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.horizontalLayout.addWidget(self.pushButton_Cancel)
        self.verticalLayout_2.addWidget(self.frame_checks)
        self.textEdit_Main = QtWidgets.QTextEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_Main.sizePolicy().hasHeightForWidth())
        self.textEdit_Main.setSizePolicy(sizePolicy)
        self.textEdit_Main.setObjectName("textEdit_Main")
        self.verticalLayout_2.addWidget(self.textEdit_Main)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Preview)
        QtCore.QMetaObject.connectSlotsByName(Preview)

    def retranslateUi(self, Preview):
        _translate = QtCore.QCoreApplication.translate
        Preview.setWindowTitle(_translate("Preview", "Preview"))
        self.checkBox_Filt1.setText(_translate("Preview", "Filter 1"))
        self.checkBox_Filt2.setText(_translate("Preview", "Filter 2"))
        self.pushButton_Paste.setText(_translate("Preview", "Paste into document"))
        self.pushButton_Cancel.setText(_translate("Preview", "Cancel"))
