# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'waiting.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormWaiting(object):
    def setupUi(self, FormWaiting):
        FormWaiting.setObjectName("FormWaiting")
        FormWaiting.resize(331, 93)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/mfmclogo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FormWaiting.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(FormWaiting)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(FormWaiting)
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.progressBar = QtWidgets.QProgressBar(FormWaiting)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)

        self.retranslateUi(FormWaiting)
        QtCore.QMetaObject.connectSlotsByName(FormWaiting)

    def retranslateUi(self, FormWaiting):
        _translate = QtCore.QCoreApplication.translate
        FormWaiting.setWindowTitle(_translate("FormWaiting", "OCR"))
        self.label_2.setText(_translate("FormWaiting", "<html><head/><body><p><span style=\" font-size:12pt;\">Performing OCR. Please wait....</span></p></body></html>"))
import textbox_rc
